### ISSUE TITLE
Strange error occurred when I clicked on the costumes tab

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#3023]
gui.js:9410 
        
       Uncaught TypeError: this.object.thumbnail is not a function
    at CostumeIconMorph.<anonymous> (gui.js:9410:50)
    at CostumeIconMorph.createThumbnail (gui.js:9886:47)
    at CostumeIconMorph.init (gui.js:9877:10)
    at new CostumeIconMorph (gui.js:9823:10)
    at gui.js:10367:16
    at Array.forEach (<anonymous>)
    at WardrobeMorph.updateList (gui.js:10366:36)
    at WardrobeMorph.init (gui.js:10262:10)
    at new WardrobeMorph (gui.js:10248:10)
    at IDE_Morph.createSpriteEditor (gui.js:1891:29)

And here's how it looked:

![image](https://user-images.githubusercontent.com/2138696/161025548-4b650873-4eaf-45d1-ac6d-8b7e3284cb36.png)

Reloading didn't fix the problem. Here's the project:

https://drive.google.com/file/d/1unROy6AHDVKASx1uWj5iiMprXtPioIfO/view?usp=sharing

Just click the costumes tab of the first sprite.

Perhaps relevant is that the first two sprites were exported from other projects and imported into this one.

**Comment by ToonTalk** [comment]
I worked around the problem by editing the XML so that there were empty lists in the <costume> element.

**Comment by ToonTalk** [comment]
Perhaps I should have mentioned that the sprites never were given a custom costume.
